### ISSUE TITLE
Download Everything Script

### ISSUE THREAD

**Issue by dvdcd** [WiiDatabase/PyNUSD#1]
With the closure of the wiishop coming near, it's gotten me worried about if the NU servers are still going to be up, so is there a script that will just download everything from the NUS and pack it into wads? i know your NUSD mod has this, but it doesn't pack it into wads

**Comment by Brawl345** [comment]
Here: https://gist.githubusercontent.com/Brawl345/51ea0b5c877392cc1877baaadb324040/raw/pynusd_mirror_system_files.py
Place it in the same directory as pynusd, install `xmltodict` via pip and double click it/run it with Python. It will **only download system titles** like IOS and Channels (Weather Channel, EULA, etc.) and pack them as WADs. It uses my [up-to-date NUS-Database](https://github.com/WiiDatabase/NUS-Database).

By default it will mirror the CDN structure so one can easily host their own CDN. You can adjust the behaviour near the end of the file by changing `cdndir=True` to `False`.
