### ISSUE TITLE
please compile!!

### ISSUE THREAD

**Issue by yardmith** [WiiDatabase/PyNUSD#6]
can you please compile it and make a exe

**Comment by Brawl345** [comment]
Python is not a compiled language and packing it is a nightmare. Just install Python 3 from the Windows Store or python.org, [download this repo](https://github.com/WiiDatabase/PyNUSD/archive/refs/heads/master.zip), unpack the ZIP, open a command prompt in the same folder and type `pip install -U -r requirements.txt`. Then you can use it.
