### ISSUE TITLE
Automatic TitleKey Generation

### ISSUE THREAD

**Issue by buggii** [WiiDatabase/PyNUSD#7]
It is now possible to add the automatic titlekey generation for Wii/WiiWares/DSi using https://github.com/dojafoja/Kii-U-Generator (this is for WiiU but just change the common key to the one specific for the console you want to); tested with latest version of your PyNUSD. I suppose it can be done for your 3DS tool too !

**Comment by Brawl345** [comment]
It was added on 16th July 2020 in the rewrite branch: https://github.com/WiiDatabase/PyNUSD/commit/aaeb1117fd7124902ebbc522aa74bf40f63947f8
I am not interested in further development of PyNUSD, sorry.  The rewrite branch is nearly finished I think, only thing missing is WAD creating (?) and NUS downloading.
For 3DS I think you need one of the common keys, it's a bit more complicated. I have stopped development of 3DS-NUSD in 2019 though.
